import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, MapPin } from "lucide-react";
import { profile } from "../data/content";

export const metadata: Metadata = { title: "Profile", description: "About Muhammad Shahroze, an Android engineer focused on production-ready Kotlin products.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  return <main id="main-content" className="page-shell pt-[4.75rem]" tabIndex={-1}>
    <header className="container-wide grid gap-10 py-14 md:py-20 lg:grid-cols-[1.25fr_.75fr] lg:items-end"><div><p className="eyebrow">Profile / 01</p><h1 className="display-lg mt-7 max-w-[12ch]">I build the parts users see—and the systems that keep them working.</h1></div><div><p className="body-xl">I&apos;m Muhammad Shahroze, an Android engineer with {profile.experience} of experience turning feature-heavy product requirements into dependable Kotlin applications.</p><p className="mt-7 flex gap-3 border-t border-black/20 pt-5 text-sm leading-relaxed text-stone-600"><MapPin size={17} className="mt-1 shrink-0 text-blue-700" />{profile.location}<br />{profile.relocation} · {profile.timezone}</p></div></header>
    <section className="editorial-panel"><div className="container-wide grid gap-12 py-16 md:py-24 lg:grid-cols-[.6fr_1.4fr]"><p className="eyebrow">The short version</p><div className="space-y-7 text-2xl leading-[1.35] tracking-[-.025em] text-stone-300 md:text-4xl"><p>My recent work spans maps, scheduling, media, AI-backed identification, system utilities, billing, monetization, Firebase, and inherited production codebases.</p><p>I personally engineered the supplied from-scratch Android applications within a wider team environment. I own my implementation work while respecting product, design, backend, publishing, and leadership contributions.</p><p className="text-white">I&apos;m looking for remote work with US and European teams, hybrid opportunities in Islamabad, focused freelance products, and collaborations with a real technical problem at the center.</p></div></div></section>
    <section className="section"><div className="container-wide grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Current direction</p><h2 className="display-md mt-5">Android now. Intelligent systems next.</h2></div><div><p className="body-xl">{profile.educationStatus}</p><div className="mt-9 grid gap-0"><Link href="/experience" className="index-link"><span className="index-number">01</span><strong className="font-display text-2xl">Career and education</strong><ArrowUpRight size={17} /></Link><Link href="/skills" className="index-link"><span className="index-number">02</span><strong className="font-display text-2xl">Technical skills</strong><ArrowUpRight size={17} /></Link><Link href="/ai-workflow" className="index-link"><span className="index-number">03</span><strong className="font-display text-2xl">AI-assisted workflow</strong><ArrowUpRight size={17} /></Link><Link href="/process" className="index-link"><span className="index-number">04</span><strong className="font-display text-2xl">Engineering process</strong><ArrowUpRight size={17} /></Link><Link href="/contact" className="index-link"><span className="index-number">05</span><strong className="font-display text-2xl">Start a conversation</strong><ArrowUpRight size={17} /></Link></div></div></div></section>
  </main>;
}
