import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";

export const metadata: Metadata = { title: "Process", description: "Engineering principles and AI-assisted workflow used by Muhammad Shahroze.", alternates: { canonical: "/process" } };
const principles = [["Useful before flashy", "Begin with the actual job and failure states, then shape the interface around clarity."], ["Architecture earns speed", "Clear state and boundaries make products easier to change without hiding complexity."], ["Production is the design", "Performance, recovery, permissions, analytics, and release behavior are part of the experience."]];

export default function ProcessPage() {
  return <main id="main-content" className="page-shell pt-[4.75rem]" tabIndex={-1}><header className="container-wide py-14 md:py-20"><p className="eyebrow">Process / 05</p><h1 className="display-lg mt-7 max-w-[12ch]">A clear path from problem to dependable release.</h1><p className="body-xl mt-8 max-w-3xl">Architecture, privacy, code review, testing, Play policy, and the shipped result remain my responsibility—whether the work starts from a blank project or an inherited codebase.</p></header><section className="border-section"><div className="container-wide grid gap-12 py-12 md:py-20 lg:grid-cols-[.65fr_1.35fr]"><h2 className="display-md">Principles that survive changing tools.</h2><div>{principles.map(([title, copy], index) => <article key={title} className="grid gap-4 border-t border-black/25 py-7 md:grid-cols-[3rem_.7fr_1.3fr]"><span className="index-number">0{index + 1}</span><h3 className="font-display text-2xl font-semibold">{title}</h3><p className="leading-relaxed text-stone-600">{copy}</p></article>)}</div></div></section><section className="editorial-panel"><div className="container-wide flex flex-col items-start justify-between gap-8 py-12 md:flex-row md:items-end md:py-20"><div><p className="eyebrow">Tools behind the process</p><h2 className="display-md mt-6 max-w-4xl">See how AI supports the work without replacing ownership.</h2></div><div className="flex flex-wrap gap-3"><Link href="/ai-workflow" className="button button-secondary">AI workflow <ArrowUpRight size={14} /></Link><Link href="/contact" className="button button-secondary">Discuss a problem <ArrowUpRight size={14} /></Link></div></div></section></main>;
}
