import type { Metadata } from "next";
import Link from "next/link";
import { Mail } from "lucide-react";
import { profile } from "../data/content";

export const metadata: Metadata = { title: "Privacy", description: "How this portfolio handles analytics and contact-form information.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return <main id="main-content" className="page-shell pt-28" tabIndex={-1}><header className="section-tight"><div className="container"><p className="eyebrow">Privacy notice</p><h1 className="display-lg mt-7">Clear data boundaries.</h1><p className="body-xl mt-7 max-w-3xl">This portfolio collects only what is needed to understand site use and respond to inquiries. It does not sell personal information.</p><p className="mt-5 font-mono text-[0.65rem] uppercase tracking-[0.1em] text-zinc-600">Last updated August 12, 2026</p></div></header><section className="border-section pb-24"><div className="container prose"><h2 id="analytics">Vercel Analytics</h2><p>The site uses Vercel Analytics to understand aggregate page visits and privacy-safe interactions such as project opens, résumé downloads, and contact outcomes. Names, email addresses, company names, messages, phone numbers, and form contents are not sent as analytics properties.</p><h2 id="contact">Contact form data</h2><p>When you submit the contact form, the site processes your name, email, inquiry type, message, and any optional company, link, timeline, or budget information you provide. The data is used only to deliver and respond to your inquiry.</p><p>The form runs through a Vercel serverless function and sends the inquiry through Resend. No database is used and the application does not write submissions to the server filesystem. Email providers may retain delivery records according to their own policies.</p><h2 id="spam">Spam protection</h2><p>Cloudflare Turnstile evaluates whether a submission is legitimate. Its single-use token is validated on the server before an email is sent. The site does not use the challenge result for advertising profiles.</p><h2 id="retention">Retention and control</h2><p>Messages remain in the recipient email account only as long as reasonably needed for correspondence, opportunity records, security, or legal obligations. You may request correction or deletion of an inquiry by contacting the address below, subject to legitimate record-keeping requirements.</p><h2 id="security">What not to send</h2><p>Do not submit passwords, API keys, access tokens, private source code, payment details, health data, or user data through the contact form.</p><h2 id="contact-rights">Questions or requests</h2><p>Contact <a className="text-cyan underline underline-offset-4" href={`mailto:${profile.email}`}>{profile.email}</a> for privacy questions or data requests.</p><Link href="/contact" className="button button-primary mt-9"><Mail size={15} /> Contact Muhammad</Link></div></section></main>;
}
