import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";

export const metadata: Metadata = { title: "Engagements", description: "Ideal Android engagements, deliverables, confidentiality, and scope boundaries.", alternates: { canonical: "/services/engagements" } };
const fit = ["A new native Android application or substantial feature", "A codebase with recurring crashes, ANRs, or release risk", "An XML/Compose modernization workstream", "Billing, RevenueCat, subscriptions, or one-time purchases", "Ad placement, premium surfaces, analytics, and remote configuration", "Maps, Firebase, Room, Ktor, media, sensor, or device integrations"];
const deliverables = ["Implementation plan and risk map", "Production-quality Android code", "State, error, empty, and recovery flows", "Analytics and monitoring hooks", "Testing and rollout checklist", "Technical handoff documentation"];

export default function EngagementsPage() { return <main id="main-content" className="page-shell pt-[4.75rem]" tabIndex={-1}><header className="container-wide py-14 md:py-20"><p className="eyebrow">Services / Engagements</p><h1 className="display-lg mt-7 max-w-[11ch]">Engagements with a clear Android outcome.</h1></header><section className="border-section"><div className="container-wide grid gap-14 py-12 md:py-20 lg:grid-cols-2"><div><h2 className="font-display text-4xl font-semibold tracking-[-.05em]">A good fit</h2><ol className="mt-8">{fit.map((item, index) => <li key={item} className="index-link"><span className="index-number">0{index + 1}</span><span>{item}</span><span /></li>)}</ol></div><div><h2 className="font-display text-4xl font-semibold tracking-[-.05em]">Typical deliverables</h2><ol className="mt-8">{deliverables.map((item, index) => <li key={item} className="index-link"><span className="index-number">0{index + 1}</span><span>{item}</span><span /></li>)}</ol></div></div></section><section className="editorial-panel"><div className="container-wide grid gap-10 py-14 md:grid-cols-2 md:py-20"><div><p className="eyebrow">Confidentiality and ownership</p><p className="body-xl mt-6">Your source, product information, and business data remain yours. I do not reuse employer-owned code, private interfaces, or confidential metrics.</p></div><div><p className="eyebrow">Not offered</p><p className="body-xl mt-6">Guaranteed revenue outcomes, copied proprietary modules, deceptive monetization, policy-violating implementations, or vague work without access and acceptance criteria.</p></div><Link href="/contact?type=freelance" className="button button-secondary w-fit">Start an inquiry <ArrowUpRight size={14} /></Link></div></section></main>; }
